services:
  whatsmiau2:
    build: .
    image: whatsmiau2:latest
    ports:
      - "8085:8081"
    environment:
      - PORT=8081
      - DEBUG_MODE=false
      - DEBUG_WHATSMEOW=false
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - DIALECT_DB=sqlite3
      - DB_URL=file:/app/data/data.db?_foreign_keys=on
      - API_KEY=2wtLvtb20wXePp8D9uRhm55aCjINiciO
      - CONFIG_SESSION_PHONE_VERSION=2.3000.2.2413.51
      - CONFIG_SESSION_PHONE_CLIENT=Chrome
      - CONFIG_SESSION_PHONE_NAME=Chrome (Windows)
      - QRCODE_LIMIT=30
      - CACHE_REDIS_ENABLED=true
    volumes:
      - whatsmeow-data:/app/data
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  qrserver:
    build:
      context: .
      dockerfile: Dockerfile.qrserver
    image: qrserver:latest
    ports:
      - "3001:3000"
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  network_swarm_public:
    external: true

volumes:
  redis-data:
    driver: local
  whatsmeow-data:
    driver: local
